sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t spikelabs/corebos-formatter -f ./docker/Dockerfile .

script:
#  - docker run spikelabs/corebos-formatter phpcs.phar --standard=build/cbSR/ci.xml --extensions=inc,js,php,service `cat build/cbSR/cifiles`
  - docker run spikelabs/corebos-formatter eslint -c build/cbSR/eslintci.js `cat build/cbSR/cifilesjs`
#  - docker run spikelabs/corebos-formatter find . -not -path "./.git/*" -type f -perm /u=x,g=x,o=x -print | sort | diff build/cbSR/executables -
  - docker run spikelabs/corebos-formatter find . -not -path "./build/WebserviceVQLParser/*" -not -path "./include/PhpSpreadsheet/*" -not -path "./include/install/resources/gdinfo.php" -type f \( -name \*.php -o -name \*.service -o -name \*.inc \) -exec build/cbSR/chksyntax {} \;

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

deploy:
  provider: script
  script: bash deployment/deploy.sh
  on:
    branch: master